### ISSUE TITLE
Tie is reported as loss.

### ISSUE THREAD

**Issue by Mineinjava** [CCShambots/ShamPit-Display#1]
It appears that when a tie occurs, it is reported as a loss

<img width="1610" alt="image" src="https://github.com/CCShambots/ShamPit-Display/assets/65673396/010e767d-e24a-4967-ad07-033d2cbbbd50">

In the top left corner the display reads "just lost Quals 59 62-62".
62-62 is a tie, and is accurately reported on the blue alliance as a tie.
https://www.thebluealliance.com/match/2024casj_qm59

**Comment by J-Barta** [comment]
My apologies it took so long to respond...  I didn't have notifications on for new issues. This should be corrected in versions 2024.2.7 and above.
